### ISSUE TITLE
Unencrypted `password-store` entries are backed up

### ISSUE THREAD

**Issue by josephmturner** [emacscollective/no-littering#200]
As noted [here](https://lonely.town/@wasamasa/110227701055899570), `pass` entries are backed up in plain text when `backup-directory-alist` is set to `nil`.

**Comment by tarsius** [comment]
Thanks for letting me know!

**Comment by josephmturner** [comment]
@tarsius  Thank you for the quick response!!

**Comment by tarsius** [comment]
I have made a new release 1.3.0. Update to that or if you are using Melpa a snapshot from today. (It's around midnight, the timestamp will probably be 20230420.x, not 20230420.x. The last affected snapshot is 20230410.852.

`no-littering` no longer sets `backup-directory-alist`. The default is `nil`, meaning that backups are created in the same directory as the file being edited.

`pass` uses `/dev/shm` or if that doesn't exist `/tmp`. Usually these directories use tmpfs, so any files saved there (whether backup or not), do not hit a disk. I.e., they don't survive a reboot.

The impact of this issue is that the backup files for files in those directories (and other tmpfs directories) *did* survive reboots.

**Comment by sjrmanning** [comment]
I get why this is being fixed, but it also means updating this project without any config changes means I suddenly have `$newfile~` files everywhere. Might be helpful to update the README with a second option (if I get some time this weekend, happy to take a stab at it).

**Comment by tarsius** [comment]
It was past midnight and I wanted to get a fix out. I'll add a note about customizing this variable to the documentation, but it might take a few days -- I wouldn't want to recommend something unsafe.

Customizing `auto-save-file-name-transforms` as suggested seems unsafe too. I will have to look into that as well.

**Comment by ajgrf** [comment]
It may also be worth mentioning in the readme that packages like `undo-fu-session` (and others that restore undo history) deserve the same treatment. I don't think you need to detail exactly how to configure every package that might store sensitive information, but maybe there should be a list of packages that require special attention.

**Comment by tarsius** [comment]
@ajgrf I've just opened #203 for this.

**Comment by tarsius** [comment]
Add link to https://www.reddit.com/r/emacs/comments/12tj72z for reference.
