### ISSUE TITLE
Theme `tutorial--saved-dir`

### ISSUE THREAD

**Issue by yantar92** [emacscollective/no-littering#202]
Emacs tutorial can be modified. That modified version is saved according to `tutorial--saved-dir`, which is hard-coded to `(locate-user-emacs-file "tutorial/")`. It would be nice to theme it though. At least, via advice. Possibly also adding a customization to Emacs upstream.

**Comment by tarsius** [comment]
I don't think that many people who are still learning the very basics of Emacs would worry about where the modified tutorial is saved. `(locate-user-emacs-file "tutorial/")` seems like a very good location to save it, *because* that location is very visible -- that makes it easier to start over if they somehow mess up the tutorial.

The symbol prefix of `tutorial--saved-dir`, the fact that it is a function and that the location is hard-coded, indicates that the Emacs developers also think that this should not be customizable.

Even if it were customizable, it still wouldn't make sense to theme it here, since a complete beginner has much more pressing needs than keeping their `~/.config/emacs` clean.
