### ISSUE TITLE
Don't override image-dired-thumbnail-storage but set to follow xdg

### ISSUE THREAD

**Issue by Thaodan** [emacscollective/no-littering#219]
Image-dired can use XDG Thumbnail managing standard Unixes such as Linux/BSD who follow Xdg.

no-littering should try to check if Emacs is 29.1 and any of the above mentioned OS's are used.

**Comment by tarsius** [comment]
> Don't override image-dired-thumbnail-storage but set to follow xdg

I disagree. `no-littering` is about moving stuff to subdirectories of `~/.config/emacs`, instead of cluttering that directory itself. That's the feature the documentation advertises.

Of course a user who appreciates that, is also likely to approve of xdg, but even if one does, one may still want all the emacs things in somewhere below `~/.config/emacs`.

If one doesn't use any other applications that use thumbnails, then there is no reason to put the thumbnails in a location where they are shared with other applications.

Setting these `image-dired-*` options does not interfere with your desire to use xdg. If you set `image-dired-thumbnail-storage`, then these other options will simply be ignored.

```elisp
(defcustom image-dired-dir (locate-user-emacs-file "image-dired/")
  "Directory where thumbnail images are stored.

The value of this option is ignored if Image-Dired is customized
to use the Thumbnail Managing Standard; they will be saved in
\"$XDG_CACHE_HOME/thumbnails/\" instead.  See
`image-dired-thumbnail-storage'."
  :type 'directory)
```
