### ISSUE TITLE
no-littering is littering during compilation

### ISSUE THREAD

**Issue by binarin** [emacscollective/no-littering#249]
When emacs init file containing
```emacs-lisp

(setq no-littering-etc-directory "/custom/dir/etc"
      no-littering-var-directory "/custom/dir/var")

(use-package no-littering
  :ensure t)
```
is being automatically and asynchronously native compiled by emacs, the `etc` and `var` directories are being created in their default location `~/.emacs.d/` instead of the custom one.  The same happens if one tries to byte-compile init file explicitly, e.g. in batch mode.

While it's possible to wrap `setq` above in `eval-and-compile`, it'll only keep user's `.emacs.d` clean. 

But the underlying problem of littering during compilation will still be there - ideally no directory creation should happen at top-level of `.el` file. Instead such actions should be wrapped in a function similar to `no-littering-theme-backups`  - either to be called by user explicitly, or maybe added to some hook.

**Comment by binarin** [comment]
@Rid1FZ  That's in the  very eginning of my `init.el`:
```emacs-lisp
;;; -*- lexical-binding: t -*-
(eval-and-compile
  (defvar xdg-cache-home
    (or (getenv "XDG_CACHE_HOME")
        (expand-file-name "~/.cache")))

  (defun cache-file-name (&rest components)
    (apply #'file-name-concat xdg-cache-home "emacs" components))

  (setq package-user-dir (cache-file-name "elpa/")
        no-littering-etc-directory (cache-file-name "no-littering" "config")
        no-littering-var-directory (cache-file-name "no-littering" "data")
        native-comp-async-env-modifier-form `(setq package-directory-list ',package-directory-list)))

(use-package no-littering
  :ensure t)
```

**Comment by tarsius** [comment]
> But the underlying problem of littering during compilation will still be there - ideally no directory creation should happen at top-level of `.el` file.

IMO these are two separate issues.

1. There's indeed a convention that merely loading a library should not ... do stuff. Maybe I should follow that here, but in practice that would mean that users would just add `(no-littering-make-directories)` to their existing `no-littering` configuration; and once they have done that, the behavior would be the same as what we have now.

2. No directories are created when `no-littering.el` is being compiled but, as you report, when the init file is being compiled *and* doing that happens to cause `no-littering` to be loaded, then directories are being created at this time.

   I don't think this second situation can reliably be detected [^1]. So, if it is undesirable, then we have to prevent it, and as far as I can tell, that has to happen outside of `no-littering.el`.

[^1]: Okay, maybe `byte-compile-current-file` could be used, but that is undocumented.

> While it's possible to wrap `setq` above in `eval-and-compile`, it'll only keep user's `.emacs.d` clean.

Or to put it differently, the directories are being created where we want them to be created, but "not at the time we want it to happen".

Never-the-less, I think that is a fine solution. There are other considerations beyond "doing the right thing", including backward compatibility.

Putting the code that creates directories inside a function, which users have to call in their init file, would break backward compatibility. Besides, if we don't create directories unless some new function is called explicitly, then maybe we should not set variable without some new function explicitly being called. If we did *that* then backward compatibility would definitely be broken; the configuration of everyone who setup `no-littering` before we make that change would be *broken*.

So what about simply not loading `no-littering` when `init.el` is being compiled?

This won't work:

```elisp
(progn ; (cl-eval-when (load eval) ...) is the same
  (setq no-littering-etc-directory  ...)
  (setq no-littering-var-directory  ...)
  (require 'no-littering))
```

That doesn't work because certain forms are treated differently (i.e., they *are* evaluated at compile time) if they are located at the top-level **or** inside a top-level `progn`.

We can get around that:

```elisp
(progn
  (setq no-littering-etc-directory  ...)
  (setq no-littering-var-directory  ...)
  (funcall 'require 'no-littering))
```

Not sure I want to add that to the readme, because we couldn't just gloss over the `funcall` and would instead have to explain why that is necessary, which would be rather confusing to non-elisp-experts.

I think this would be better

```elisp
(eval-and-compile ; Ensure values don't differ at compile time.
  (setq no-littering-etc-directory  ...)
  (setq no-littering-var-directory  ...)
  (require 'no-littering))
```

, because I think we could get away with just that comment.

Sure, this would still create the directories while `init.el` is being compiled, but would you even have noticed that this happened, if they had not been created in the wrong location to begin with?

**Comment by binarin** [comment]
The full story about `use-package` is that it forces `require` automatically during compile-time - and it's absolutely reasonable, as otherwise variables assignments will produce undefined warnings. 

So this is what I'm using currently to untangle  this situtation (by not allowing `use-package` to do anything during compile time at all):

```emacs-lisp
     (cl-eval-when '(load eval)
       (eval `(use-package no-littering
                :ensure t
                :init
                (setf no-littering-etc-directory (cache-file-name "no-littering" "config"))
                (setf no-littering-var-directory (cache-file-name "no-littering" "data")))))
```

Looks like adding `(cl-eval-when '(load eval)  ...)` to `no-littering` is the right solution to this problem (and without relying on the undocumented ` byte-compile-current-file`)

**Comment by binarin** [comment]
It's my excessive perfectionism mostly :smile:  But also random warnings when byte-compilation happens in a hermetic environment (e.g. as part of NixOS packaging).

When I changed `no-littering` to allow it to proceed with setting vars even when the configured directories are not writeable,  I've found that a bunch of other packages also try to create files during load, or add them to `kill-emacs-hook`.  

So in the end I don't think any changes to `no-littering` can help with this situation. I've just put the following snippte at the beginning of my `init.el`, so that if it's being compiled by standalone emacs invocation, every non-cooperating package can  write to a temp dir to their heart's content:

```emacs-lisp
(defvar xdg-cache-home
  (or (getenv "XDG_CACHE_HOME")
      (expand-file-name "~/.cache")))

(defun cache-file-name (&rest components)
  (apply #'file-name-concat xdg-cache-home "emacs" components))

;; If no-littering is not loaded, it means that standalone compilation
;; happens right now. There are a bunch of packages doing IO even
;; during load (or adding it to various hooks/eval-when-load'ing),
;; let's give them a safe playground.
;; NOTE: `(use-package no-littering)` below is mandatory!
(eval-when-compile
  (unless (featurep 'no-littering)
    (setf user-emacs-directory (make-temp-file "throwaway-emacs.d-for-compilation" t))))

(defvar no-littering-etc-directory (cache-file-name "no-littering" "config"))
(defvar no-littering-var-directory (cache-file-name "no-littering" "data"))
(setq package-user-dir (cache-file-name "elpa/"))

(use-package no-littering
  :ensure t)

```
